# NameError
print(val)

# ValueError
num = int('ChatGIS')

# IndexError
my_list = [1, 2, 3]
# val1 = my_list[5]

# KeyError
dict1 = {
    'name': 'ChatGIS',
    'blog': 'https://chatgis.space/'
}
print(dict1['name'])
# print(dict1['age'])

# AttributeError
# my_list.add(4)

# TypeError
num = 10
string = "20"
# result = num + string